// Audio mix. Every file lives in public/ and is generated by scripts/, so a
// render never depends on third-party audio. Swap any file for your own with
// the same name (e.g. a licensed track at public/music/bed.wav).
export const AUDIO = {
  voice: true,
  voiceVolume: 1,
  music: true,
  musicVolume: 0.07,
  /** Music dips to this fraction of musicVolume while the narrator speaks. */
  musicDuck: 0.55,
  sfx: true,
  sfxVolume: 0.42,
};

export type SfxName =
  | "whoosh"
  | "impact"
  | "tick"
  | "key"
  | "pop"
  | "deny"
  | "success"
  | "ping"
  | "lock"
  | "glitch"
  | "riser";

/** Per-effect trim so the effects sit at a similar loudness. */
export const SFX_GAIN: Record<SfxName, number> = {
  whoosh: 0.35,
  impact: 0.9,
  tick: 0.25,
  key: 0.18,
  pop: 0.35,
  deny: 0.6,
  success: 0.55,
  ping: 0.5,
  lock: 0.5,
  glitch: 0.45,
  riser: 0.4,
};
